### ISSUE TITLE
Flickering Issue

### ISSUE THREAD

**Issue by LaFesta1749** [Thundermaker300/ScriptedEvents#55]
Hello @Thundermaker300,

Not sure how to describe this but if having ScriptedEvents in the server and having plugin(s) showing hints on the screen, the ScriptedEvents makes them flicker and disappear almost instantly.

Having ScriptedEvents disabled fixes that issue.

The only script that I have on the server is Auto Nuke:

```
!-- AUTORUN
# Wait until the round has started
WAITUNTIL {ROUNDSTARTED}

# Wait for the amount of seconds
WAITSEC 1200

# Do not activate the warhead again if it's already detonated or counting down
STOPIF {WARHEADDETONATED}

# Activate warhead
WARHEAD START

# Lock the warhead so its setting can't be changed
WARHEAD LOCK

# Broadcast that the warhead has been automatically started and cannot be cancelled.
BROADCAST 10 <color=#FF0000>WARNING: WARHEAD HAS BEEN AUTOMATICALLY ACTIVATED AND CANNOT BE STOPPED. PLEASE ESCAPE THE FACILITY!
```

**Comment by Elektryk-Andrzej** [comment]
Do you have RueI installed? There have been known issues with SE's implementation of RueI, which could've lead to this behavior.

**Comment by LaFesta1749** [comment]
> Do you have RueI installed? There have been known issues with SE's implementation of RueI, which could've lead to this behavior.

Yes, I have Ruel installed but the issue was before installing Ruel.

**Comment by Elektryk-Andrzej** [comment]
afaik scripted events is not doing anything with hints by itself, it uses the exileds implementation for showing hints
only explanation for that behavior would be that se is trying to display hints all the time, but no hint action is used in your script
maybe @Thundermaker300 would know more about it

**Comment by Jraylor** [comment]
Has this been resolved at all yet @Elektryk-Andrzej @Thundermaker300?
